services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/x_gate_db
      - JWT_SECRET=jwt_secret
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=x_gate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: